### ISSUE TITLE
As a logged-in user, I want to be able to access a map of Zurich that displays all car parks at their respective location in order to interactively explore (i.e., swiping and zooming) which car park is closest to the future destination. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs22-group-03/sopra-fs22-group-03-client#12]
**Acceptance Criteria:**

- [x] The car parks and their free parking spaces are displayed on the map.
- [x] The map can be zoomed in and out. 
- [x] By clicking on the tag of a car park, the user is redirected to the detailed page of the clicked car park (see sopra-fs22-group-03/sopra-fs22-group-03-server#5). 

**Development Tasks:**
- [x] sopra-fs22-group-03/sopra-fs22-group-03-server#75
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#13
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#14
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#15
- [x] sopra-fs22-group-03/sopra-fs22-group-03-client#17
